UPDATE ORDERS SET AMT=NULL WHERE O_Num=3010;
UPDATE ORDERS SET AMT=0000 WHERE O_Num=3002;
SELECT * from ORDERS;

-- Q1 
SELECT * from ORDERS where AMT!=0 OR AMT!=NULL;
-- Q2
SELECT SP.*, C.Rating
FROM SALES_PEOPLE AS SP
JOIN CUSTOMERS AS C ON SP.S_Num = C.S_Num
ORDER BY SP.City, C.Rating;
-- Q3
SELECT * from CUSTOMERS 
WHERE Rating>100 OR City="Rome";
-- Q4
SELECT C.*,SP.S_Name 
FROM CUSTOMERS AS C
JOIN SALES_PEOPLE AS SP ON SP.S_Num = C.S_Num
WHERE SP.S_Name="Robert" OR SP.S_Name="Jessica";
-- Q5
SELECT * FROM CUSTOMERS 
WHERE C_Name LIKE "T%" OR C_Name LIKE "H%";
-- Q6
SELECT COUNT(*) FROM ORDERS 
WHERE ORDER_DATE=STR_TO_DATE('03-OCT-2023', '%d-%b-%Y'); 
-- Q7
SELECT C_Num,MIN(AMT) FROM ORDERS 
GROUP BY C_Num;
-- Q8
SELECT Order_Date,COUNT( DISTINCT S_Num) FROM ORDERS
 GROUP BY Order_Date;
-- Q9
SELECT City,MAX(Rating) FROM CUSTOMERS
GROUP BY CITY; 
-- Q10
SELECT Rating,C_Name,C_Num FROM  CUSTOMERS
ORDER BY Rating DESC;
